title: Default Page
icon: 📃

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          showToc:
            label: Show Table of Contents
            type: toggle
            default: false
            help: Display a table of contents based on headings
            width: 1/2
          text:
            label: Content
            type: blocks
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
