title: Site

tabs:
  pages:
    label: Pages
    icon: page
    sections:
      pages:
        type: pages
  settings:
    label: settings
    icon: settings
    fields:
      mainMenu:
        label: Main Menu
        type: pages
        multiple: true
        required: true
      legal:
        label: Legal
        type: textarea
        help: Legal text for site footer
